title: "Brock's Bodybuilding Journal"
description: "Training logs and exercise notes"
profile_image: /assets/images/bmf.png
accent_color: "#F6E27F"
theme: minima

collections:
  exercises:
    output: true
    permalink: /exercises/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: exercises
    values:
      layout: exercise